In [32]:
import pandas as pd

In [33]:
df=pd.read_csv("StudentsPerformance.csv")

In [34]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [35]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [36]:
df.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [38]:
df.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [39]:
df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [40]:
df.duplicated().sum()

np.int64(0)

In [41]:
df.shape

(1000, 8)

In [42]:
std=df[columns].std()
std

15.163080096009468

In [43]:
categarical_columns=["gender","race/ethnicity","parental level of education","lunch","test preparation course","math score","reading score","writing score"]

In [44]:
for column in categarical_columns:
    df[column]=df[column].astype(str).str.strip().str.lower()

In [45]:
df[column]

0      74
1      88
2      93
3      44
4      75
       ..
995    95
996    55
997    65
998    77
999    86
Name: writing score, Length: 1000, dtype: object

In [48]:
score_columns=["math score","reading score","writing score"]

In [55]:
for columns in score_columns:
    mean=df[columns].mean()
    median=df[columns].median()
    mode=(df[columns].mode()[0])

In [57]:
print("mean_score",mean)
print("median_score",median)
print("mode_score",mode)

mean_score 68.054
median_score 69.0
mode_score 74

In [63]:
for columns in score_columns:
    mean=df[columns].mean()
    median=df[columns].median()
    mode=df[columns].mode()
    std=df[columns].std()
    Q1=df[columns].quantile(0.25)
    Q3=df[columns].quantile(0.75)

In [64]:
print("mean_score",mean)
print("median_score",median)
print("mode_score",mode)
print("Q1",Q1)
print("Q3",Q3)

mean_score 68.054
median_score 69.0
mode_score 0    74
Name: writing score, dtype: int64
Q1 57.75
Q3 79.0

In [73]:
for columns in ["math score", "reading score", "writing score"]:
    IQR=Q3-Q1
    Lower=Q1-1.5*IQR
    Upper=Q3+1.5*IQR
    Outliers=df[(df[columns]<Lower) | 
               (df[columns]>Upper)]
    
    print("outliers in", columns)
    print(Outliers[columns])

outliers in math score
17     18
59      0
145    22
338    24
466    26
787    19
842    23
980     8
Name: math score, dtype: int64
outliers in reading score
59     17
76     26
327    23
596    24
980    24
Name: reading score, dtype: int64
outliers in writing score
59     10
76     22
327    19
596    15
980    23
Name: writing score, dtype: int64

In [85]:
performance = []
for Percentage in df["Percentage"]:
    if Percentage >= 90:
        performance.append("Excellent")
    elif Percentage >= 75:
        performance.append("Very good")
    elif Percentage >= 60:
        performance.append("good")
    elif Percentage >= 50:
        performance.append("Average")
    else:
        performance.append("need a improment")

df["performance"] = performance
print(df[["performance","performance"]])

          performance       performance
0                good              good
1           Very good         Very good
2           Excellent         Excellent
3    need a improment  need a improment
4           Very good         Very good
..                ...               ...
995         Excellent         Excellent
996           Average           Average
997              good              good
998              good              good
999         Very good         Very good

[1000 rows x 2 columns]

In [86]:
df["Total marks"]=df[score_columns].sum(axis=1)

In [87]:
df["Percentage"]=(df["Total marks"]/300)*100

In [89]:
print(df[score_columns+["Total marks","Percentage"]])

     math score  reading score  writing score  Total marks  Percentage
0            72             72             74          218   72.666667
1            69             90             88          247   82.333333
2            90             95             93          278   92.666667
3            47             57             44          148   49.333333
4            76             78             75          229   76.333333
..          ...            ...            ...          ...         ...
995          88             99             95          282   94.000000
996          62             55             55          172   57.333333
997          59             71             65          195   65.000000
998          68             78             77          223   74.333333
999          77             86             86          249   83.000000

[1000 rows x 5 columns]

In [90]:
df.to_csv("cleaned_student_performance.csv",index=False)

In [91]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Percentage,performance,Total marks
0,female,group b,bachelor's degree,standard,none,72,72,74,72.666667,good,218
1,female,group c,some college,standard,completed,69,90,88,82.333333,Very good,247
2,female,group b,master's degree,standard,none,90,95,93,92.666667,Excellent,278
3,male,group a,associate's degree,free/reduced,none,47,57,44,49.333333,need a improment,148
4,male,group c,some college,standard,none,76,78,75,76.333333,Very good,229
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group e,master's degree,standard,completed,88,99,95,94.000000,Excellent,282
996,male,group c,high school,free/reduced,none,62,55,55,57.333333,Average,172
997,female,group c,high school,free/reduced,completed,59,71,65,65.000000,good,195
998,female,group d,some college,standard,completed,68,78,77,74.333333,good,223
999,female,group d,some college,free/reduced,none,77,86,86,83.000000,Very good,249