In [1]:
import pandas as pd

In [7]:
df=pd.read_csv("stock_data_50_records.csv")

In [8]:
df

          Date    Open    High     Low   Close    Volume
0   2026-01-02  101.09  103.37  100.08  102.04   89377.0
1   2026-01-05  101.05  101.99   99.91  100.58   88404.0
2   2026-01-06  102.41  103.15   99.47  101.36   94045.0
3   2026-01-07  105.35  108.05  103.53  106.87   72352.0
4   2026-01-08  105.13  109.88  104.24  107.49   79790.0
5   2026-01-09  104.91  108.22  103.42  107.07   81919.0
6   2026-01-12  107.95  109.49  104.84  106.57   45600.0
7   2026-01-13  109.53  111.44  107.88     NaN   69124.0
8   2026-01-14  108.89  111.08  107.60  109.85   67643.0
9   2026-01-15  110.07  114.76  109.21  112.32   80764.0
10  2026-01-16  109.43  111.85  108.13  108.77   49007.0
11  2026-01-19  108.79  109.79  106.87  108.72  450000.0
12  2026-01-20  109.43  110.92  105.67  107.52   96835.0
13  2026-01-21  106.18  107.28  102.64  104.09   77410.0
14  2026-01-22  103.28  106.28  102.27  105.21   84080.0
15  2026-01-23  102.47  106.05  101.45  105.48   80447.0
16  2026-01-26  100.84  102.72   99.25  101.00   48208.0
17  2026-01-27  101.61  105.43   99.76  103.92   96491.0
18  2026-01-28  100.18  101.80   98.35  101.20       NaN
19  2026-01-29   97.83   98.89   95.17   96.84   58589.0
20  2026-01-09  104.91  108.22  103.42  107.07   81919.0
21  2026-02-02  100.47  104.83   99.84  103.85   57453.0
22  2026-02-03  100.79  101.81  100.05  101.02   76212.0
23  2026-02-04   98.42  103.33   96.57  101.85   83525.0
24  2026-02-05   97.64  100.11   91.29   92.70   87202.0
25  2026-02-06   98.04  100.96   97.53   99.98   72635.0
26  2026-02-09   96.17   98.48   95.52   96.64   73828.0
27  2026-02-10   97.05   99.07   95.25   96.75  620000.0
28  2026-02-11   96.17   97.63   95.66   96.65   43420.0
29  2026-02-12   95.84   97.80   91.42   92.16   71216.0
30  2026-02-13   94.96   96.20   93.50   94.82   40301.0
31  2026-02-16   98.49  101.26   96.95   99.50   85236.0
32  2026-02-17   98.67     NaN   97.19  101.93   89758.0
33  2026-02-18   96.96   98.53   95.38   96.22   92322.0
34  2026-02-19   98.64   99.32   95.75   97.32   40699.0
35  2026-01-22  103.28  106.28  102.27  105.21   84080.0
36  2026-02-23   97.22  100.49   96.23   99.35   98483.0
37  2026-02-24   93.89   95.72   92.27   94.85   40190.0
38  2026-02-25   91.70   92.28   89.47   90.94   50492.0
39  2026-02-26   92.26   95.27   90.49   93.59   90132.0
40  2026-02-27   93.79   96.14   92.30   94.28   75743.0
41  2026-03-02   94.30   97.07   92.95   96.54  850000.0
42  2026-03-03   94.29   95.81   92.55   93.19   90336.0
43  2026-03-04   93.95   94.90   92.54   93.59   92479.0
44  2026-03-05     NaN   93.27   90.10   91.00   59778.0
45  2026-03-06   90.39   91.24   86.89   87.76   97471.0
46  2026-03-09   89.76   92.53   87.80   90.65   66641.0
47  2026-02-06   98.04  100.96   97.53   99.98   72635.0
48  2026-03-11   92.68   95.36   90.84   92.99   72745.0
49  2026-03-12   89.71   90.49   88.09   89.54   95006.0

In [9]:
df.head()

         Date    Open    High     Low   Close   Volume
0  2026-01-02  101.09  103.37  100.08  102.04  89377.0
1  2026-01-05  101.05  101.99   99.91  100.58  88404.0
2  2026-01-06  102.41  103.15   99.47  101.36  94045.0
3  2026-01-07  105.35  108.05  103.53  106.87  72352.0
4  2026-01-08  105.13  109.88  104.24  107.49  79790.0

In [11]:
df.tail()

          Date   Open    High    Low  Close   Volume
45  2026-03-06  90.39   91.24  86.89  87.76  97471.0
46  2026-03-09  89.76   92.53  87.80  90.65  66641.0
47  2026-02-06  98.04  100.96  97.53  99.98  72635.0
48  2026-03-11  92.68   95.36  90.84  92.99  72745.0
49  2026-03-12  89.71   90.49  88.09  89.54  95006.0

In [14]:
df["Date"]=pd.to_datetime(df["Date"])

In [12]:
df.dtypes

Date       object
Open      float64
High      float64
Low       float64
Close     float64
Volume    float64
dtype: object

In [13]:
df.isnull().sum()

Date      0
Open      1
High      1
Low       0
Close     1
Volume    1
dtype: int64

In [15]:
df=df.dropna()

In [16]:
df.isnull().sum()

Date      0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [17]:
df.duplicated().sum()

np.int64(3)

In [24]:
df["Price_delta"]=df["Close"]-df["Open"]

C:\Users\YAJNESH\AppData\Local\Temp\ipykernel_19228\3643404153.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Price_delta"]=df["Close"]-df["Open"]

In [25]:
df

         Date    Open    High     Low   Close    Volume  Price_delta
0  2026-01-02  101.09  103.37  100.08  101.09   89377.0          0.0
1  2026-01-05  101.05  101.99   99.91  101.05   88404.0          0.0
2  2026-01-06  102.41  103.15   99.47  102.41   94045.0          0.0
3  2026-01-07  105.35  108.05  103.53  105.35   72352.0          0.0
4  2026-01-08  105.13  109.88  104.24  105.13   79790.0          0.0
5  2026-01-09  104.91  108.22  103.42  104.91   81919.0          0.0
6  2026-01-12  107.95  109.49  104.84  107.95   45600.0          0.0
8  2026-01-14  108.89  111.08  107.60  108.89   67643.0          0.0
9  2026-01-15  110.07  114.76  109.21  110.07   80764.0          0.0
10 2026-01-16  109.43  111.85  108.13  109.43   49007.0          0.0
11 2026-01-19  108.79  109.79  106.87  108.79  450000.0          0.0
12 2026-01-20  109.43  110.92  105.67  109.43   96835.0          0.0
13 2026-01-21  106.18  107.28  102.64  106.18   77410.0          0.0
14 2026-01-22  103.28  106.28  102.27  103.28   84080.0          0.0
15 2026-01-23  102.47  106.05  101.45  102.47   80447.0          0.0
16 2026-01-26  100.84  102.72   99.25  100.84   48208.0          0.0
17 2026-01-27  101.61  105.43   99.76  101.61   96491.0          0.0
19 2026-01-29   97.83   98.89   95.17   97.83   58589.0          0.0
20 2026-01-09  104.91  108.22  103.42  104.91   81919.0          0.0
21 2026-02-02  100.47  104.83   99.84  100.47   57453.0          0.0
22 2026-02-03  100.79  101.81  100.05  100.79   76212.0          0.0
23 2026-02-04   98.42  103.33   96.57   98.42   83525.0          0.0
24 2026-02-05   97.64  100.11   91.29   97.64   87202.0          0.0
25 2026-02-06   98.04  100.96   97.53   98.04   72635.0          0.0
26 2026-02-09   96.17   98.48   95.52   96.17   73828.0          0.0
27 2026-02-10   97.05   99.07   95.25   97.05  620000.0          0.0
28 2026-02-11   96.17   97.63   95.66   96.17   43420.0          0.0
29 2026-02-12   95.84   97.80   91.42   95.84   71216.0          0.0
30 2026-02-13   94.96   96.20   93.50   94.96   40301.0          0.0
31 2026-02-16   98.49  101.26   96.95   98.49   85236.0          0.0
33 2026-02-18   96.96   98.53   95.38   96.96   92322.0          0.0
34 2026-02-19   98.64   99.32   95.75   98.64   40699.0          0.0
35 2026-01-22  103.28  106.28  102.27  103.28   84080.0          0.0
36 2026-02-23   97.22  100.49   96.23   97.22   98483.0          0.0
37 2026-02-24   93.89   95.72   92.27   93.89   40190.0          0.0
38 2026-02-25   91.70   92.28   89.47   91.70   50492.0          0.0
39 2026-02-26   92.26   95.27   90.49   92.26   90132.0          0.0
40 2026-02-27   93.79   96.14   92.30   93.79   75743.0          0.0
41 2026-03-02   94.30   97.07   92.95   94.30  850000.0          0.0
42 2026-03-03   94.29   95.81   92.55   94.29   90336.0          0.0
43 2026-03-04   93.95   94.90   92.54   93.95   92479.0          0.0
45 2026-03-06   90.39   91.24   86.89   90.39   97471.0          0.0
46 2026-03-09   89.76   92.53   87.80   89.76   66641.0          0.0
47 2026-02-06   98.04  100.96   97.53   98.04   72635.0          0.0
48 2026-03-11   92.68   95.36   90.84   92.68   72745.0          0.0
49 2026-03-12   89.71   90.49   88.09   89.71   95006.0          0.0

In [26]:
df["Daily_Return"]=(df["Close"]-df["Open"]/df["Open"])*100

C:\Users\YAJNESH\AppData\Local\Temp\ipykernel_19228\3311838851.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Daily_Return"]=(df["Close"]-df["Open"]/df["Open"])*100

In [27]:
df

,Date,Open,High,Low,Close,Volume,Price_delta,Daily_Return
0,2026-01-02,101.09,103.37,100.08,101.09,89377.0,0.0,10009.0
1,2026-01-05,101.05,101.99,99.91,101.05,88404.0,0.0,10005.0
2,2026-01-06,102.41,103.15,99.47,102.41,94045.0,0.0,10141.0
3,2026-01-07,105.35,108.05,103.53,105.35,72352.0,0.0,10435.0
4,2026-01-08,105.13,109.88,104.24,105.13,79790.0,0.0,10413.0
5,2026-01-09,104.91,108.22,103.42,104.91,81919.0,0.0,10391.0
6,2026-01-12,107.95,109.49,104.84,107.95,45600.0,0.0,10695.0
8,2026-01-14,108.89,111.08,107.60,108.89,67643.0,0.0,10789.0
9,2026-01-15,110.07,114.76,109.21,110.07,80764.0,0.0,10907.0
10,2026-01-16,109.43,111.85,108.13,109.43,49007.0,0.0,10843.0
11,2026-01-19,108.79,109.79,106.87,108.79,450000.0,0.0,10779.0
12,2026-01-20,109.43,110.92,105.67,109.43,96835.0,0.0,10843.0
13,2026-01-21,106.18,107.28,102.64,106.18,77410.0,0.0,10518.0
14,2026-01-22,103.28,106.28,102.27,103.28,84080.0,0.0,10228.0
15,2026-01-23,102.47,106.05,101.45,102.47,80447.0,0.0,10147.0
16,2026-01-26,100.84,102.72,99.25,100.84,48208.0,0.0,9984.0
17,2026-01-27,101.61,105.43,99.76,101.61,96491.0,0.0,10061.0
19,2026-01-29,97.83,98.89,95.17,97.83,58589.0,0.0,9683.0
20,2026-01-09,104.91,108.22,103.42,104.91,81919.0,0.0,10391.0
21,2026-02-02,100.47,104.83,99.84,100.47,57453.0,0.0,9947.0
22,2026-02-03,100.79,101.81,100.05,100.79,76212.0,0.0,9979.0
23,2026-02-04,98.42,103.33,96.57,98.42,83525.0,0.0,9742.0
24,2026-02-05,97.64,100.11,91.29,97.64,87202.0,0.0,9664.0
25,2026-02-06,98.04,100.96,97.53,98.04,72635.0,0.0,9704.0
26,2026-02-09,96.17,98.48,95.52,96.17,73828.0,0.0,9517.0
27,2026-02-10,97.05,99.07,95.25,97.05,620000.0,0.0,9605.0
28,2026-02-11,96.17,97.63,95.66,96.17,43420.0,0.0,9517.0
29,2026-02-12,95.84,97.80,91.42,95.84,71216.0,0.0,9484.0
30,2026-02-13,94.96,96.20,93.50,94.96,40301.0,0.0,9396.0
31,2026-02-16,98.49,101.26,96.95,98.49,85236.0,0.0,9749.0
33,2026-02-18,96.96,98.53,95.38,96.96,92322.0,0.0,9596.0
34,2026-02-19,98.64,99.32,95.75,98.64,40699.0,0.0,9764.0
35,2026-01-22,103.28,106.28,102.27,103.28,84080.0,0.0,10228.0
36,2026-02-23,97.22,100.49,96.23,97.22,98483.0,0.0,9622.0
37,2026-02-24,93.89,95.72,92.27,93.89,40190.0,0.0,9289.0
38,2026-02-25,91.70,92.28,89.47,91.70,50492.0,0.0,9070.0
39,2026-02-26,92.26,95.27,90.49,92.26,90132.0,0.0,9126.0
40,2026-02-27,93.79,96.14,92.30,93.79,75743.0,0.0,9279.0
41,2026-03-02,94.30,97.07,92.95,94.30,850000.0,0.0,9330.0
42,2026-03-03,94.29,95.81,92.55,94.29,90336.0,0.0,9329.0
43,2026-03-04,93.95,94.90,92.54,93.95,92479.0,0.0,9295.0
45,2026-03-06,90.39,91.24,86.89,90.39,97471.0,0.0,8939.0
46,2026-03-09,89.76,92.53,87.80,89.76,66641.0,0.0,8876.0
47,2026-02-06,98.04,100.96,97.53,98.04,72635.0,0.0,9704.0
48,2026-03-11,92.68,95.36,90.84,92.68,72745.0,0.0,9168.0
49,2026-03-12,89.71,90.49,88.09,89.71,95006.0,0.0,8871.0

In [28]:
df["Volume"].mean()

np.float64(111812.21739130435)

In [29]:
df["Volume"].max()

850000.0

In [32]:
df["Volume_MA_7"]=df["Volume"].rolling(7).mean()

C:\Users\YAJNESH\AppData\Local\Temp\ipykernel_19228\1611078686.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Volume_MA_7"]=df["Volume"].rolling(7).mean()

In [33]:
df

,Date,Open,High,Low,Close,Volume,Price_delta,Daily_Return,Volume_MA_7
0,2026-01-02,101.09,103.37,100.08,101.09,89377.0,0.0,10009.0,NaN
1,2026-01-05,101.05,101.99,99.91,101.05,88404.0,0.0,10005.0,NaN
2,2026-01-06,102.41,103.15,99.47,102.41,94045.0,0.0,10141.0,NaN
3,2026-01-07,105.35,108.05,103.53,105.35,72352.0,0.0,10435.0,NaN
4,2026-01-08,105.13,109.88,104.24,105.13,79790.0,0.0,10413.0,NaN
5,2026-01-09,104.91,108.22,103.42,104.91,81919.0,0.0,10391.0,NaN
6,2026-01-12,107.95,109.49,104.84,107.95,45600.0,0.0,10695.0,78783.857143
8,2026-01-14,108.89,111.08,107.60,108.89,67643.0,0.0,10789.0,75679.000000
9,2026-01-15,110.07,114.76,109.21,110.07,80764.0,0.0,10907.0,74587.571429
10,2026-01-16,109.43,111.85,108.13,109.43,49007.0,0.0,10843.0,68153.571429
11,2026-01-19,108.79,109.79,106.87,108.79,450000.0,0.0,10779.0,122103.285714
12,2026-01-20,109.43,110.92,105.67,109.43,96835.0,0.0,10843.0,124538.285714
13,2026-01-21,106.18,107.28,102.64,106.18,77410.0,0.0,10518.0,123894.142857
14,2026-01-22,103.28,106.28,102.27,103.28,84080.0,0.0,10228.0,129391.285714
15,2026-01-23,102.47,106.05,101.45,102.47,80447.0,0.0,10147.0,131220.428571
16,2026-01-26,100.84,102.72,99.25,100.84,48208.0,0.0,9984.0,126569.571429
17,2026-01-27,101.61,105.43,99.76,101.61,96491.0,0.0,10061.0,133353.000000
19,2026-01-29,97.83,98.89,95.17,97.83,58589.0,0.0,9683.0,77437.142857
20,2026-01-09,104.91,108.22,103.42,104.91,81919.0,0.0,10391.0,75306.285714
21,2026-02-02,100.47,104.83,99.84,100.47,57453.0,0.0,9947.0,72455.285714
22,2026-02-03,100.79,101.81,100.05,100.79,76212.0,0.0,9979.0,71331.285714
23,2026-02-04,98.42,103.33,96.57,98.42,83525.0,0.0,9742.0,71771.000000
24,2026-02-05,97.64,100.11,91.29,97.64,87202.0,0.0,9664.0,77341.571429
25,2026-02-06,98.04,100.96,97.53,98.04,72635.0,0.0,9704.0,73933.571429
26,2026-02-09,96.17,98.48,95.52,96.17,73828.0,0.0,9517.0,76110.571429
27,2026-02-10,97.05,99.07,95.25,97.05,620000.0,0.0,9605.0,152979.285714
28,2026-02-11,96.17,97.63,95.66,96.17,43420.0,0.0,9517.0,150974.571429
29,2026-02-12,95.84,97.80,91.42,95.84,71216.0,0.0,9484.0,150260.857143
30,2026-02-13,94.96,96.20,93.50,94.96,40301.0,0.0,9396.0,144086.000000
31,2026-02-16,98.49,101.26,96.95,98.49,85236.0,0.0,9749.0,143805.142857
33,2026-02-18,96.96,98.53,95.38,96.96,92322.0,0.0,9596.0,146617.571429
34,2026-02-19,98.64,99.32,95.75,98.64,40699.0,0.0,9764.0,141884.857143
35,2026-01-22,103.28,106.28,102.27,103.28,84080.0,0.0,10228.0,65324.857143
36,2026-02-23,97.22,100.49,96.23,97.22,98483.0,0.0,9622.0,73191.000000
37,2026-02-24,93.89,95.72,92.27,93.89,40190.0,0.0,9289.0,68758.714286
38,2026-02-25,91.70,92.28,89.47,91.70,50492.0,0.0,9070.0,70214.571429
39,2026-02-26,92.26,95.27,90.49,92.26,90132.0,0.0,9126.0,70914.000000
40,2026-02-27,93.79,96.14,92.30,93.79,75743.0,0.0,9279.0,68545.571429
41,2026-03-02,94.30,97.07,92.95,94.30,850000.0,0.0,9330.0,184160.000000
42,2026-03-03,94.29,95.81,92.55,94.29,90336.0,0.0,9329.0,185053.714286
43,2026-03-04,93.95,94.90,92.54,93.95,92479.0,0.0,9295.0,184196.000000
45,2026-03-06,90.39,91.24,86.89,90.39,97471.0,0.0,8939.0,192379.000000
46,2026-03-09,89.76,92.53,87.80,89.76,66641.0,0.0,8876.0,194686.000000
47,2026-02-06,98.04,100.96,97.53,98.04,72635.0,0.0,9704.0,192186.428571
48,2026-03-11,92.68,95.36,90.84,92.68,72745.0,0.0,9168.0,191758.142857
49,2026-03-12,89.71,90.49,88.09,89.71,95006.0,0.0,8871.0,83901.857143

In [37]:
Volume_mean=df["Volume"].mean()
Volume_mean

np.float64(111812.21739130435)

In [38]:
Volume_std=df["Volume"].std()
Volume_std

148250.65636907922

In [39]:
Volume_threshol=Volume_mean+(2*Volume_std)

In [42]:
anomalies=df[df["Volume"]>Volume_threshol]
anomalies

,Date,Open,High,Low,Close,Volume,Price_delta,Daily_Return,Volume_MA_7
11,2026-01-19,108.79,109.79,106.87,108.79,450000.0,0.0,10779.0,122103.285714
27,2026-02-10,97.05,99.07,95.25,97.05,620000.0,0.0,9605.0,152979.285714
41,2026-03-02,94.30,97.07,92.95,94.30,850000.0,0.0,9330.0,184160.000000

In [44]:
mean_return=df["Daily_Return"].mean()
variance_return=df["Daily_Return"].var()
standard_return=df["Daily_Return"].std()

In [49]:
print("Daily_Return Statistics")
print("mean_Return",mean_return)
print("variance_return",variance_return)
print("standard_return",standard_return)

Daily_Return Statistics
mean_Return 9848.95652173913
variance_return 322966.08695652185
standard_return 568.3010531017181

In [50]:
df

,Date,Open,High,Low,Close,Volume,Price_delta,Daily_Return,Volume_MA_7
0,2026-01-02,101.09,103.37,100.08,101.09,89377.0,0.0,10009.0,NaN
1,2026-01-05,101.05,101.99,99.91,101.05,88404.0,0.0,10005.0,NaN
2,2026-01-06,102.41,103.15,99.47,102.41,94045.0,0.0,10141.0,NaN
3,2026-01-07,105.35,108.05,103.53,105.35,72352.0,0.0,10435.0,NaN
4,2026-01-08,105.13,109.88,104.24,105.13,79790.0,0.0,10413.0,NaN
5,2026-01-09,104.91,108.22,103.42,104.91,81919.0,0.0,10391.0,NaN
6,2026-01-12,107.95,109.49,104.84,107.95,45600.0,0.0,10695.0,78783.857143
8,2026-01-14,108.89,111.08,107.60,108.89,67643.0,0.0,10789.0,75679.000000
9,2026-01-15,110.07,114.76,109.21,110.07,80764.0,0.0,10907.0,74587.571429
10,2026-01-16,109.43,111.85,108.13,109.43,49007.0,0.0,10843.0,68153.571429
11,2026-01-19,108.79,109.79,106.87,108.79,450000.0,0.0,10779.0,122103.285714
12,2026-01-20,109.43,110.92,105.67,109.43,96835.0,0.0,10843.0,124538.285714
13,2026-01-21,106.18,107.28,102.64,106.18,77410.0,0.0,10518.0,123894.142857
14,2026-01-22,103.28,106.28,102.27,103.28,84080.0,0.0,10228.0,129391.285714
15,2026-01-23,102.47,106.05,101.45,102.47,80447.0,0.0,10147.0,131220.428571
16,2026-01-26,100.84,102.72,99.25,100.84,48208.0,0.0,9984.0,126569.571429
17,2026-01-27,101.61,105.43,99.76,101.61,96491.0,0.0,10061.0,133353.000000
19,2026-01-29,97.83,98.89,95.17,97.83,58589.0,0.0,9683.0,77437.142857
20,2026-01-09,104.91,108.22,103.42,104.91,81919.0,0.0,10391.0,75306.285714
21,2026-02-02,100.47,104.83,99.84,100.47,57453.0,0.0,9947.0,72455.285714
22,2026-02-03,100.79,101.81,100.05,100.79,76212.0,0.0,9979.0,71331.285714
23,2026-02-04,98.42,103.33,96.57,98.42,83525.0,0.0,9742.0,71771.000000
24,2026-02-05,97.64,100.11,91.29,97.64,87202.0,0.0,9664.0,77341.571429
25,2026-02-06,98.04,100.96,97.53,98.04,72635.0,0.0,9704.0,73933.571429
26,2026-02-09,96.17,98.48,95.52,96.17,73828.0,0.0,9517.0,76110.571429
27,2026-02-10,97.05,99.07,95.25,97.05,620000.0,0.0,9605.0,152979.285714
28,2026-02-11,96.17,97.63,95.66,96.17,43420.0,0.0,9517.0,150974.571429
29,2026-02-12,95.84,97.80,91.42,95.84,71216.0,0.0,9484.0,150260.857143
30,2026-02-13,94.96,96.20,93.50,94.96,40301.0,0.0,9396.0,144086.000000
31,2026-02-16,98.49,101.26,96.95,98.49,85236.0,0.0,9749.0,143805.142857
33,2026-02-18,96.96,98.53,95.38,96.96,92322.0,0.0,9596.0,146617.571429
34,2026-02-19,98.64,99.32,95.75,98.64,40699.0,0.0,9764.0,141884.857143
35,2026-01-22,103.28,106.28,102.27,103.28,84080.0,0.0,10228.0,65324.857143
36,2026-02-23,97.22,100.49,96.23,97.22,98483.0,0.0,9622.0,73191.000000
37,2026-02-24,93.89,95.72,92.27,93.89,40190.0,0.0,9289.0,68758.714286
38,2026-02-25,91.70,92.28,89.47,91.70,50492.0,0.0,9070.0,70214.571429
39,2026-02-26,92.26,95.27,90.49,92.26,90132.0,0.0,9126.0,70914.000000
40,2026-02-27,93.79,96.14,92.30,93.79,75743.0,0.0,9279.0,68545.571429
41,2026-03-02,94.30,97.07,92.95,94.30,850000.0,0.0,9330.0,184160.000000
42,2026-03-03,94.29,95.81,92.55,94.29,90336.0,0.0,9329.0,185053.714286
43,2026-03-04,93.95,94.90,92.54,93.95,92479.0,0.0,9295.0,184196.000000
45,2026-03-06,90.39,91.24,86.89,90.39,97471.0,0.0,8939.0,192379.000000
46,2026-03-09,89.76,92.53,87.80,89.76,66641.0,0.0,8876.0,194686.000000
47,2026-02-06,98.04,100.96,97.53,98.04,72635.0,0.0,9704.0,192186.428571
48,2026-03-11,92.68,95.36,90.84,92.68,72745.0,0.0,9168.0,191758.142857
49,2026-03-12,89.71,90.49,88.09,89.71,95006.0,0.0,8871.0,83901.857143